add components
yehorDiakonov/traineeRN pull request #1
Opened 2021-05-19 08:57 UTC by yehorDiakonov

2021-05-20 09:39 UTC, BogdanKusch requested changes
Please check all points.

2021-05-20 09:39 UTC, BogdanKusch commented on src/explore/actions/creators.tsx
> +export const logout = (value:boolean) => ({type: 'LOGOUT', data: value});
Please rename arguments name to valid meaning, for example:
```login = (username: string) => ({...});```

2021-05-20 09:39 UTC, BogdanKusch commented on src/explore/actions/types.tsx
> +export const LOGOUT = 'LOGOUT';
We can use enum for this, for example:
```
export enum AuthActions {
 Auth = 'AUTH',
 Login = 'LOGIN',
 ...
 }
 ```

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +import AsyncStorage from '@react-native-async-storage/async-storage';
Split imports from packages and local files.

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +    auth: (value:boolean) => void
Rename value argument ...

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +    const onChangePassword = (data:string):void => {
useless function, you can use directly setInputPassword.

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +            const setStatus = async() => await saveStatusToStorage('true');
useless func that you call right after initialisation.

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Main/index.tsx
> +    authSet?: Function,
Define signature for authSet callback

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Main/index.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(Main);
Avoid default export

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +    state: any,
Dont use any

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +import MainContainer from '../../components/MainContainer';
Split imports from packages and local files

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +    const Tab = createMaterialTopTabNavigator();
You can create this variable outside of Navbar func

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +const mapStateToProps = (state: IState) => {
minimise this func

2021-05-20 09:39 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +export default connect(mapStateToProps)(Navbar);
Lets avoid to use default export

2021-05-20 11:50 UTC, BogdanKusch requested changes
please check all points.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContainer/index.tsx
> +    addList: (value:[])=>void,
value???
refresh, what is the value?

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContainer/index.tsx
> +    removeList: ()=>void
white spaces ```() => void```

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContainer/index.tsx
> +}
func is not minimised, example:

```
const mapStateToProps = (...) => ({
state,
});
```

And dont pass all root state to component.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContainer/index.tsx
> +}
Func is not minimised.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    refresh: (value:boolean)=>void,
addList, value - argument? please provide valid name for arg.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    state: IState
We still using IState interface name.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +        let result = await axios.get(`https://picsum.photos/v2/list?page=${state.count}&limit=8`)
why we use await and in the same time using then for Promise?

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    async function getImgs() {
Lets use arrow functions.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    function handleRefreshing() {
Lets use arrow functions.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    function handleLoadMore() {
Lets use arrow functions.
And this func is useless because call only 1 another func.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +                renderItem={({ item }) => {
Lest export item to another component.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +const ProfileComponent:React.FC<Props> = (props:Props) => {
no need to use props: Props because we alredy define React.FC<Props>

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +        const logout = async () => {
this func is useless.
You call it in next line.

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +                        uri: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw8QDxAODw8PDg8NDw8NEA0ODQ8NDw8OFhEWFxUVFRUYHSggGBomGxUVITEhJSkrMC4uGB8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKy
please use url to image beside base64

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +const mapStateToProps = (state: IState) => {
minimise func

2021-05-20 11:50 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +const mapDispatchToProps = (dispatch: Dispatch<Action>) => {
minimise func

2021-05-20 11:50 UTC, BogdanKusch commented on src/navigation/index.tsx
> +        const statusAuth = async () => {
useless func because you call it in next line

2021-05-20 11:50 UTC, BogdanKusch commented on src/navigation/index.tsx
> +const mapStateToProps = (state: IState) => {
minimise func

2021-05-20 11:50 UTC, BogdanKusch commented on src/navigation/index.tsx
> +const mapDispatchToProps = (dispatch: Dispatch<Action>) => {
min function

2021-05-20 11:50 UTC, BogdanKusch commented on src/reducers/index.ts
> +export interface IState {
?

2021-05-21 10:50 UTC, BogdanKusch requested changes

2021-05-21 10:50 UTC, BogdanKusch commented on src/components/ImageItem/index.tsx
> +interface Item {
This is implementation of component, and this is Props interface, please rename interface name to Props.

2021-05-21 10:50 UTC, BogdanKusch commented on src/components/ImageItem/styles.ts
> +});
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/explore/actions/types.tsx
> +}
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +export const MainContainer = connect(mapStateToProps, mapDispatchToProps)(MainContainerComponent);
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +    {list, count, refresh, setCount, setRefresh, addList, removeList}: Props) => {
in one line, no destrcuturing argument on new line.

2021-05-21 10:50 UTC, BogdanKusch commented on src/features/MainContent/index.tsx
> +                onEndReached={() => getImgs()}
we can pass here getImgs as call back directly no need to use dump arrow function here.

2021-05-21 10:50 UTC, BogdanKusch commented on src/features/MainContent/styles.ts
> +});
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/navigation/index.tsx
> +export const MainNavigator =  connect(mapStateToProps, mapDispatchToProps)(MainNavigatorComponent);
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/reducers/authReducer.ts
> +import {AnyAction} from 'redux'
First import from libs, second from local files

2021-05-21 10:50 UTC, BogdanKusch commented on src/reducers/authReducer.ts
> +}
Please add new line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/reducers/imagesReducer.ts
> +import {AnyAction} from 'redux'
First import from libs, second from local files

2021-05-21 10:50 UTC, BogdanKusch commented on src/reducers/imagesReducer.ts
> +}
1 empty line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/reducers/index.ts
> +
1 empty line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +import {AuthState} from './../../reducers/authReducer';
No need to split local file imports here.

2021-05-21 10:50 UTC, BogdanKusch commented on src/screens/Login/index.tsx
> +export const Login = connect(mapStateToProps, mapDispatchToProps)(LoginScreen);
1 empty line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +}
1 empty line in the end of file.

2021-05-21 10:50 UTC, BogdanKusch commented on src/screens/Navbar/index.tsx
> +const Tab = createMaterialTopTabNavigator();
tab?
HomeTopTab

2021-05-21 16:04 UTC, BogdanKusch requested changes

2021-05-24 07:53 UTC, BogdanKusch requested changes
please check all points.

2021-05-24 07:53 UTC, BogdanKusch commented on App.tsx
> +export const App = () => {
minimise func. ```App = () => ({...})```

2021-05-24 07:53 UTC, BogdanKusch commented on src/components/ImageItem/index.tsx
> +export const ItemImage: React.FC<Props> = ({url, author}) => {
minimise func.

2021-05-24 07:53 UTC, BogdanKusch commented on src/components/MyButton/index.tsx
> +export const MyButton = (props: any) => {
min func.

2021-05-24 07:53 UTC, BogdanKusch commented on src/components/MyButton/index.tsx
> +      <View style={{...styles.container, ...props.style}}>
Here we can use array, please check style prop you can pass array of styles.

2021-05-24 07:53 UTC, BogdanKusch commented on src/components/MyButton/index.tsx
> +export const MyButton = (props: any) => {
define Props interface

2021-05-24 07:53 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +  const active: null | any = useRef(null);
define useRef<T> please define T that you using.

2021-05-24 07:53 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +const saveStatusToStorage = async (status: string) =>
please define func before use it.

2021-05-24 07:53 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +            secureTextEntry={true}
secureTextEntry no need to pass true,
just define secureTextEntry as prop.

2021-05-24 07:53 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +            onChangeText={(data: string) => setInputPassword(data)}
useless arrow func.

2021-05-24 07:53 UTC, BogdanKusch commented on src/features/Splash/index.tsx
> +export const Splash = () => {
min func.

2021-05-24 07:53 UTC, BogdanKusch commented on src/navigation/MainNavigator.tsx
> +      )}
Please think how we can improve this.
because stack navigator should have 2 screens, when user authorised we should navigate to navbar otherwise to login screen.
You can play with initialScreen prop in navigation. Or navigate user to proper screen when you understand is it authorised or not.

2021-05-24 07:53 UTC, BogdanKusch commented on src/navigation/Navbar.tsx
> +  return (
min func.

2021-05-24 07:53 UTC, BogdanKusch commented on src/navigation/RootStack.tsx
> +export const RootStack = () => {
min func.

2021-05-24 11:07 UTC, BogdanKusch requested changes

2021-05-24 11:07 UTC, BogdanKusch commented on src/components/MyButton/index.tsx
> +    <View style={{...styles.container, ...props.style[0]}}>
We can use here array of styles
```style={[styles.container, ...]}```

2021-05-24 11:07 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +    navigate: Function;
Try to not use Function, define full method signature or use predefined from navigation.

2021-05-24 11:07 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +    navigate: Function
Dont use Function interface.

2021-05-24 11:07 UTC, BogdanKusch commented on src/features/Splash/index.tsx
> +    navigate: Function;
Dont use Function interface.

2021-05-24 11:38 UTC, BogdanKusch requested changes

2021-05-24 11:38 UTC, BogdanKusch commented on src/components/MyButton/index.tsx
> +  styleText: object;
Check how to define style props in React Native.

2021-05-24 11:38 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +  initialPassword: string;
Why we need this initial values?

2021-05-24 11:38 UTC, BogdanKusch commented on src/features/Splash/index.tsx
> +    }
How we can improve this, if we call 1 func but with diff arguments?

2021-05-24 11:45 UTC, yehorDiakonov commented on src/features/Login/index.tsx
> +  initialPassword: string;
this is test credentials for input on app

2021-05-24 11:52 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +  initialPassword: string;
We will resolve this in next PR, because this PR is really huge.

2021-05-24 11:52 UTC, BogdanKusch approved these changes

2021-05-24 12:04 UTC, merged