create ability to switch languages
yehorDiakonov/traineeRN pull request #3
Opened 2021-05-27 14:28 UTC by yehorDiakonov

2021-05-28 08:04 UTC, BogdanKusch commented on src/localize/index.tsx
> +export const leng = new Locale(Languages.en, {
lets define interface for this class and export this leng instance as ```export const leng: Localisation = new Locale(...)```

2021-05-28 08:04 UTC, BogdanKusch commented on src/localize/ru.ts
> +export const ru = {
lets define json file for this.

2021-05-28 09:06 UTC, BogdanKusch requested changes

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/index.tsx
> +export const leng: Language = new Locale(Languages.en, {
leng - wrong name
localisation, locale, localeService ...

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/index.tsx
> +      debug: true,
debug even for production build?

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/index.tsx
> +    translation: require('./en.json'),
you can import it by using import from latest ES.

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/ru.json
> +  "invalidPasswordMess": "не правильный пароль",
You can create object here
"errors":  {
 "worngPassword" : "..."
 ....
 }

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/ru.json
> +  "invalidPasswordMess": "не правильный пароль",
We can split localisation data in logical block, for example: errors, etc...

2021-05-28 09:06 UTC, BogdanKusch commented on src/localize/ru.json
> +  "title": "Авторизация",
not clear name when we use it...

2021-05-28 09:17 UTC, yehorDiakonov commented on src/localize/index.tsx
> +      debug: true,
i'll delete this

2021-05-28 09:18 UTC, yehorDiakonov commented on src/localize/index.tsx
> +      debug: true,
because works without this string

2021-05-28 15:31 UTC, BogdanKusch requested changes

2021-05-28 15:31 UTC, BogdanKusch commented on src/localize/index.tsx
> +    }
i18next.t(key, options); no need to use if statement.

2021-05-28 15:31 UTC, BogdanKusch commented on src/localize/index.tsx
> +  public get(key: string, options?: {}) {
{} type is not right because this object can have properties and string values.

2021-05-31 10:16 UTC, BogdanKusch requested changes

2021-05-31 10:16 UTC, BogdanKusch commented on src/localize/index.tsx
> +  get(key: string, options?: {}): string;
options arg type?

2021-05-31 10:43 UTC, BogdanKusch approved these changes

2021-05-31 10:48 UTC, merged