Redux thunk, AsyncStorage client
yehorDiakonov/traineeRN pull request #4
Opened 2021-06-01 08:52 UTC by yehorDiakonov

2021-06-01 09:26 UTC, BogdanKusch requested changes

2021-06-01 09:26 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +        await AsyncStorage.setItem(key, value);
We call the same func with diff args

2021-06-01 09:26 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +export const setDataToStorage = async (key: string, value: string | {}) => {
wrap this methods to class

2021-06-01 09:26 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +        routes: [{name: 'Navbar'}],
Lets try to use enum for navigation screens not string constants.

2021-06-01 09:26 UTC, BogdanKusch commented on src/features/Login/index.tsx
>    await AsyncStorage.setItem('status', status);
status? not clear status of what? provide valid name and what is that means

2021-06-01 09:26 UTC, BogdanKusch commented on src/features/Profile/index.tsx
>    navigation: {
We can import interface from navigation to provide valid navigation object with all valid methods etc ...

2021-06-01 09:26 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +    await setDataToStorage('lang', key);
Lets create storage service and save there keys for async storage to not have and errors and use valid keys everywhere

2021-06-01 09:26 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +      .get(`https://picsum.photos/v2/list?page=${count}&limit=8`)
Lets define api where we can pass count and dont use urls directly
For example UserApi where we can receive user with picture + name + email etc ...

2021-06-01 09:26 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +      .then(res => dispatch(addList(res.data)))
lets use async/await everywhere...

2021-06-01 09:26 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +        dispatch(setUser({name: res.data.name, email: res.data.email}))
lets use async/await everywhere...

2021-06-01 09:26 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +  return (dispatch: Dispatch) => {
you can return this directly no need curly braces

2021-06-01 12:46 UTC, yehorDiakonov commented on src/store/actions/creators.tsx
> +      .get(`https://picsum.photos/v2/list?page=${count}&limit=8`)
I can't find an api that returns an image with different data. I have an api that returns name, email

2021-06-01 13:44 UTC, BogdanKusch requested changes

2021-06-01 13:44 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +class Async {
Not good name for class, almost reserver keyword ...

2021-06-01 13:44 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +    if (data) {
Weird condition why we cant return data in any case?
Even when data is null ...

2021-06-01 13:44 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +      return JSON.parse(data);
Weird condition why we cant return data in any case?
Even when data is null ...

2021-06-01 13:44 UTC, BogdanKusch commented on src/api/service/storage.ts
> +export enum AsyncKey {
Can we create Storage class where we will save entities with valid methods names, and inject in this class AsyncStorage ...
Now we share this keys and use them through all app.

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +const saveStatusToStorage = async (statusAuth: string) =>
Dont want to have this logic in ui component maybe in thunk function ?

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Login/index.tsx
>        setStatus();
Dont want to have this logic in ui component maybe in thunk function ?

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +      setUserData();
Dont want to have this logic in ui component maybe in thunk function ?

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +type MyExtraArg = undefined;
No need to define this types :) undefined type predefined and {} also ...
And Not sure if its valid type for thunk ...

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Login/index.tsx
> +type MyExtraArg = undefined;
Redux export interface that you can use for mapDispatchToProps I suppose ...

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +    await AsyncData.set(AsyncKey.statusAuth, 'false');
ship this logic to thunk

2021-06-01 13:44 UTC, BogdanKusch commented on src/features/Profile/index.tsx
> +    await AsyncData.set(AsyncKey.lang, key);
ship this logic to thunk

2021-06-01 13:44 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +import {AsyncData} from '../../api/asyncStorage';
split imports

2021-06-01 13:44 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +  return axios.get(`https://picsum.photos/v2/list?page=${count}&limit=8`);
```
const data = await userApi.getUser(id)
data.avatar
data.email
data.name 
...
```

2021-06-01 13:44 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +  return axios.get(`https://picsum.photos/v2/list?page=${count}&limit=8`);
Lets try to create userApi with common method auth or getUser ...

2021-06-01 13:56 UTC, yehorDiakonov commented on src/api/asyncStorage.ts
> +    if (data) {
I think in this case we can return null

2021-06-01 13:58 UTC, yehorDiakonov commented on src/api/asyncStorage.ts
> +      return JSON.parse(data);
But here we can't return null because JSON.parse needs a string, not null.

2021-06-01 14:33 UTC, yehorDiakonov commented on src/features/Login/index.tsx
> +type MyExtraArg = undefined;
look really bad, but it works

2021-06-02 10:01 UTC, BogdanKusch approved these changes

2021-06-02 10:56 UTC, BogdanKusch requested changes

2021-06-02 10:56 UTC, BogdanKusch commented on App.tsx
> +    const statusAuth = await AsyncData.getStatusAuth();
getStatusAuth return type boolean

2021-06-02 10:56 UTC, BogdanKusch commented on App.tsx
> +    const language = await AsyncData.getLanguage();
getLanguage() type Languages or null

2021-06-02 10:56 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +class AsyncApiClass {
2 classes in 1 file not convenient ...

2021-06-02 10:56 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +import {AsyncKey} from '../api/service/storage';
split imports

2021-06-02 14:10 UTC, BogdanKusch requested changes

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +class AsynkMethod {
Method is not valid name for class and we don't use Class suffix for names etc ...

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/service/asyncApi.ts
> +class AsyncApiClass {
No need to add Class suffix for class name ...

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/service/asyncApi.ts
> +class AsyncApiClass {
Async prefix also provide valid name for it

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/service/asyncApi.ts
> +export const AsyncApi = new AsyncApiClass();
empty line in the end

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +class AsynkMethod {
Async is not valid name also

2021-06-02 14:10 UTC, BogdanKusch commented on src/api/service/userApi.ts
> +class userApis {
Class name should start with capital letter, and we cant use Api's as class name because we implement one API here ...

2021-06-02 14:42 UTC, BogdanKusch requested changes

2021-06-02 14:42 UTC, BogdanKusch commented on src/api/asyncStorage.ts
> +import {StoreApi} from './service/asyncApi';
File name is not aligned with class name
And export constant name is not right because we still use async keyword

2021-06-02 14:42 UTC, BogdanKusch commented on src/api/service/asyncApi.ts
> +import AsyncStorage from '@react-native-async-storage/async-storage';
File name is not right, file name = class name
export const = class name with lower case first letter ...

2021-06-02 14:42 UTC, BogdanKusch commented on src/api/service/userApi.ts
> +class UserStoreApi {
This is not Store ...

2021-06-02 14:42 UTC, BogdanKusch commented on src/store/actions/creators.tsx
> +import {Dispatch} from 'redux';
Split this file in 2
1 - common action
2 - thunk actions (no need to use class as thunk functions ....)

2021-06-03 08:04 UTC, BogdanKusch requested changes

2021-06-03 08:04 UTC, BogdanKusch commented on src/api/service/storeApi.ts
> +    await AsyncStorage.setItem(key, typeof value === 'string' ? value : data);
in any case we will do JSON.stringify this is not good, directly in ternary operator you can wrap value with stringify method in corresponding case ...

2021-06-03 08:04 UTC, BogdanKusch commented on src/api/userBox.ts
> +  public userData = (res: {}) => {
res arg type is valid?

2021-06-03 08:04 UTC, BogdanKusch commented on src/store/actions/thunkCreators.tsx
> +});
getUserFailure, addListFailure not thunk actions ...

2021-06-03 08:26 UTC, BogdanKusch approved these changes

2021-06-03 08:45 UTC, merged